<a href="https://colab.research.google.com/github/Afzal786/Soft_Computing/blob/master/MIT2019072_SOC2020_BAM_Assignment5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

#Input matrix 4 X 6
X = np.array([1,1,1,1,1,1,-1,-1,-1,-1,-1,-1,1,-1,-1,1,1,1,1,1,-1,-1,-1,-1]).reshape(4,6)

#Output matrix of 4 X 3
Y = np.array([1,1,1,-1,-1,-1,-1,1,1,1,-1,1]).reshape(4,3)

print(X)
print(Y)

[[ 1  1  1  1  1  1]
 [-1 -1 -1 -1 -1 -1]
 [ 1 -1 -1  1  1  1]
 [ 1  1 -1 -1 -1 -1]]
[[ 1  1  1]
 [-1 -1 -1]
 [-1  1  1]
 [ 1 -1  1]]


In [3]:
#Number of features in input array
m = len(X[0])

#Number of features in output array
n = len(Y[0])

#Defining the Weight matrix
W = np.zeros(m*n).reshape(m,n)

#Runing the loop on the dataset in order to calculate the weight matrix
for i in range(X.shape[0]):
  x = X[i].reshape(1,m)
  y = Y[i].reshape(1,n)
  W = W + x.T@y

print(W)

[[2. 2. 4.]
 [4. 0. 2.]
 [2. 2. 0.]
 [0. 4. 2.]
 [0. 4. 2.]
 [0. 4. 2.]]


In [0]:
#Threshold fucntion for the Bi-polar data-set  
def threshold(y):
  for i in range(y.shape[0]):
    for j in range(y.shape[1]):
      if (y[i][j] > 0):
        y[i][j] = 1
      elif (y[i][j] <= 0):
        y[i][j] = -1
  return y


In [5]:
#Testing in forward direction means X----->Y

X_test =np.array([1,-1,-1,1,1,1]).reshape(1,6)
Y_test = np.array([-1,1,1]).reshape(1,3)

Y_out = X_test@W

Y_out = threshold(Y_out)

print(Y_out)
print("Mis-matched : {}/{}".format(int(np.sum(abs(Y_out-Y_test))),Y_out.shape[1]))

[[-1.  1.  1.]]
Mis-matched : 0/3


In [6]:
#Testing in Backward direction means Y----->X

Y_input =  np.array([-1,-1,-1]).reshape(1,3)
X_output = np.array([-1,-1,-1,-1,-1,-1]).reshape(1,6)

out = Y_input@W.T

out = threshold(out)

print(out)

print("Mis-matched : {}/{}".format(int(np.sum(abs(X_output-out))),out.shape[1]))

[[-1. -1. -1. -1. -1. -1.]]
Mis-matched : 0/6
